### ISSUE TITLE
storybook test runner not working on react native template

### ISSUE THREAD

**Issue by MiguelNiblock** [dannyhw/expo-template-storybook#2]
Hey @dannyhw  I was trying the test runner in your template and the default instructions don't work. I made an issue with them, but perhaps you're in a better position to tell what the problem is. Do you have any working example of using the test runner with react or react native? I care mostly about the react server, if it easier just to get a working prototype.

https://github.com/storybookjs/test-runner/issues/123

**Comment by dannyhw** [comment]
I could be wrong but i think test runner is from storybook 6.4 so it would be due to a version mismatch. The unfortunate problem is that the on-device storybook (storybook/react-native) beta is only compatible up till 6.3 currently. If you use react native web storybook on its own without on device you can use the latest version and I think it would work.

Alternatively chromatic also runs your interaction tests so depending on your project could also be viable.

**Comment by dannyhw** [comment]
this should work now with the lastest versions of react native storybook
